# Generated by Django 2.2.4 on 2020-05-29 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='noteForTimeSlot',
            new_name='attachedFileNotes',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='attachedFile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='extraNotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='extraNotesNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='lockedDoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='lockedDoorsNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='patrol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='patrolNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='securityRisk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='securityRiskNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='timeSlotName',
            field=models.CharField(default=' ', max_length=50, verbose_name='Form Name'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='unLockedDoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='unLockedDoorsNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 29, 5, 38, 53, 432306), verbose_name='Date'),
        ),
    ]
