# Generated by Django 2.2.4 on 2020-05-31 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200529_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='officerSignature',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='report',
            name='shiftTime',
            field=models.CharField(default='2000 - 0800', max_length=50, verbose_name='Form Name'),
        ),
        migrations.AddField(
            model_name='report',
            name='totalTimeInshift',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='companyPhotoLink',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 0, 56, 18, 849237), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='firstName',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='report',
            name='lastName',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
