# Generated by Django 2.2.4 on 2020-05-31 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200531_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 1, 10, 1, 171741), verbose_name='Date'),
        ),
    ]
